{
	"name": "pl_error_handling",
	"properties": {
		"activities": [
			{
				"name": "Data flow1",
				"type": "ExecuteDataFlow",
				"dependsOn": [],
				"policy": {
					"timeout": "1.00:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"dataflow": {
						"referenceName": "ErrorRow",
						"type": "DataFlowReference",
						"datasetParameters": {
							"invalidemp": {
								"tableName": "invalidemp"
							},
							"validemp": {
								"tableName": "validemp"
							}
						}
					},
					"compute": {
						"coreCount": 8,
						"computeType": "General"
					},
					"traceLevel": "None",
					"cacheSinks": {
						"firstRowOnly": true
					}
				}
			}
		],
		"annotations": []
	}
}